services:
  - type: web
    name: Market-Value-Prediction
    env: python
    plan: free
    runtime: python
    buildCommand: |
      pyenv install 3.10.13 --skip-existing
      pyenv global 3.10.13
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    region: oregon
    branch: main
    repo: https://github.com/ncrim7/Market-Value-Prediction
    autoDeploy: true
